email_notifications/urls.py
from django.contrib import admin
from django.urls import path,include
from notifications import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.login_user,name='login_user'),
    path('home/',include('notifications.urls')),
    path('logout/',views.user_logout,name='logout'),
]

notifications/urls.py
from django.urls import path,include
from . import views

app_name= "home"

urlpatterns=[
    path('',views.home,name='home'),
    path('today/braindesk-deliverables/',views.today_braindesk_confirm,name='today_braindesk_confirm'),
    path('today/universe-deliverables/',views.today_universe_confirm,name='today_universe_confirm'),
    path('tomorrow/braindesk-deliverables/',views.tomorrow_braindesk_confirm,name='tomorrow_braindesk_confirm'),
    path('tomorrow/universe-deliverables/',views.tomorrow_universe_confirm,name='tomorrow_universe_confirm'),
    path('sales/today-deliverables',views.todaydeliverables,name='todaydeliverables'),
    path('sales/tomorrow-deliverables',views.tomorrowdeliverables,name='tomorrowdeliverables'),
    path('sales/today-deliverables/braindesk',views.today_braindesk,name='today_braindesk'),
    path('sales/today-deliverables/universe',views.today_universe,name='today_universe'),
    path('sales/today-deliverables/others',views.today_others,name='today_others'),
    path('sales/tomorrow-deliverables/braindesk',views.tomorrow_braindesk,name='tomorrow_braindesk'),
    path('sales/tomorrow-deliverables/universe',views.tomorrow_universe,name='tomorrow_universe'),
    path('sales/tomorrow-deliverables/others',views.tomorrow_others,name='tomorrow_others'),
    path('upload/',views.upload,name='upload'),
    path('sales/today-status',views.ticket_status_today,name='ticket_status_today'),
]

notifications/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import date,datetime
# Create your models here.

class Ticket(models.Model):
    Ticket_ID = models.IntegerField(unique=True)
    Subject = models.CharField(max_length=256)
    Status = models.CharField(max_length=256)
    Source = models.CharField(max_length=256)
    Type = models.CharField(max_length=256)
    Agent = models.CharField(max_length=256)
    Group = models.CharField(max_length=256)
    Created_time = models.DateTimeField(null=False)
    Product = models.CharField(max_length=256)
    Follow_up_Date = models.CharField(max_length=256,null=True)
    Estimated_Delivery_Date = models.CharField(max_length=256,null=True)
    Full_name = models.CharField(max_length=256)
    Email = models.EmailField(max_length=256)
    Company_Name = models.CharField(max_length=256)
    def __str__(self):
        return self.Subject

class Confirmed_Ticket(models.Model):
    Ticket_ID = models.IntegerField(unique=True)
    Subject = models.CharField(max_length=260,blank=True)
    Created_time = models.DateTimeField()
    updated_time = models.DateField(default=date.today())

    def __str__(self):
        return str(self.Ticket_ID)

notifications/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
import operator

from functools import reduce
from django.urls import reverse

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

from .models import Ticket,Confirmed_Ticket
from datetime import date,datetime,timedelta
from django.utils import timezone

from django.db import IntegrityError


import csv , io

from django.contrib import messages

from django.core.mail import send_mail
from django.conf import settings

from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.utils.html import strip_tags

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect('home')
            else:
                return HttpResponse("user not active contact admin")
        else:
            return HttpResponse("Invalid, If you don't have the access or forgotted your credentials please reach us on customersupport_nemili@draup.com")
    else:
        if request.user.is_authenticated:
            return HttpResponseRedirect('home')
        else:
            return render(request,'notifications/login.html',{})
@login_required(login_url = 'login_user')
def home(request):
    return render(request,'notifications/landingpage.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_user'))

def thankyou(request):
    return render(request,'notifications/thankyou.html')

@login_required(login_url = 'login_user')
def todaydeliverables(request):
    today=str(date.today())
    tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=today)
    tick_dict = {'Ticket':tickets}
    return render(request,'notifications/today_deliverables.html',context=tick_dict)

def tomorrowdeliverables(request):
    tomorrow=str(date.today()+timedelta(days=1))
    tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=tomorrow)
    tick_dict = {'Ticket':tickets}
    return render(request,'notifications/tomorrow_deliverables.html',context=tick_dict)

@login_required(login_url = 'login_user')
def today_braindesk(request):
    lis=['Braindesk Report Refresh Request','Braindesk Request']
    if request.method == "POST":
        today=str(date.today())
        tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=today,Type__in=lis)
        tick_dict = {'Ticket':tickets,'name':"Braindesk Team","url":"today/braindesk-deliverables","day":"Today"}
        #send_mail(
        #'You have Deliverable Today !!!',
        #"Good Eve !!!",
        #settings.EMAIL_HOST_USER,
        #['kesavan.ramalingam@draup.com'],
        #fail_silently=False)
        #print("mail sent sucess fully")
        html_content = render_to_string("notifications/notification1.html",context=tick_dict)
        text_content = strip_tags(html_content)
        email = EmailMultiAlternatives(
        "You have a Deliverable !!",
        text_content,
        settings.EMAIL_HOST_USER,
        ['intriguing.despot@gmail.com'],
        #cc=['kesavan.ramalingam@draup.com']
        )
        email.attach_alternative(html_content,"text/html")
        email.send()
        return todaydeliverables(request)
    else:
        today=str(date.today())
        tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=today,Type__in=lis)
        tick_dict = {'Ticket':tickets}
        return render(request,'notifications/today_braindesk_deliverables.html',context=tick_dict)

@login_required(login_url = 'login_user')
def today_universe(request):
    if request.method == "POST":
        today=str(date.today())
        tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=today,Type__icontains = 'Universe Account Addition Request')
        tick_dict = {'Ticket':tickets,'name':"Universe Team,","url":"today/universe-deliverables","day":"Today"}
        html_content = render_to_string("notifications/notification1.html",context=tick_dict)
        text_content = strip_tags(html_content)
        email = EmailMultiAlternatives(
        "You have a Deliverable !!",
        text_content,
        settings.EMAIL_HOST_USER,
        ['intriguing.despot@gmail.com'],
        #cc=['kesavan.ramalingam@draup.com']
        )
        email.attach_alternative(html_content,"text/html")
        email.send()
        return todaydeliverables(request)
    else:
        today=str(date.today())
        tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=today,Type__icontains = 'Universe Account Addition Request')
        tick_dict = {'Ticket':tickets}
        return render(request,'notifications/today_universe_deliverables.html',context=tick_dict)

@login_required(login_url = 'login_user')
def today_others(request):
    if request.method == "POST":
        today=str(date.today())
        tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=today).exclude(Type__icontains = 'Universe Account Addition Request').exclude(Type__icontains="Braindesk Request").exclude(Type__icontains="Braindesk Report Refresh Request")
        tick_dict = {'Ticket':tickets,'name':"Team,"}
        html_content = render_to_string("notifications/notification1.html",context=tick_dict)
        text_content = strip_tags(html_content)
        email = EmailMultiAlternatives(
        "You have a Deliverable !!",
        text_content,
        settings.EMAIL_HOST_USER,
        ['intriguing.despot@gmail.com'],
        #cc=['kesavan.ramalingam@draup.com']
        )
        email.attach_alternative(html_content,"text/html")
        email.send()
        return todaydeliverables(request)
    else:
        today=str(date.today())
        tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=today).exclude(Type__icontains = 'Universe Account Addition Request').exclude(Type__icontains="Braindesk Request").exclude(Type__icontains="Braindesk Report Refresh Request")
        tick_dict = {'Ticket':tickets}
        return render(request,'notifications/today_others_deliverables.html',context=tick_dict)

def today_braindesk_confirm(request):
    lis=['Braindesk Report Refresh Request','Braindesk Request']
    if request.method == "POST":
        some_var = request.POST.getlist('Ticket_ID')
        try:
            for i in some_var:
                Confirmed_Ticket.objects.update_or_create(Ticket_ID=i,Created_time=timezone.now())
        except IntegrityError:
                return HttpResponse("This ticket is already confirmed !!!")
        return thankyou(request)

    else:
        today=str(date.today())
        tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=today,Type__in=lis)
        tick_dict = {'Ticket':tickets}
        return render(request,'notifications/braindesk_confirm.html',context=tick_dict)

def today_universe_confirm(request):
    if request.method == "POST":
        some_var = request.POST.getlist('Ticket_ID')
        try:
            for i in some_var:
                Confirmed_Ticket.objects.update_or_create(Ticket_ID=i,Created_time=timezone.now())
        except IntegrityError:
                return HttpResponse("This ticket is already confirmed !!!")
        return thankyou(request)
    else:
        today=str(date.today())
        tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=today,Type__icontains="Universe Account Addition Request")
        tick_dict = {'Ticket':tickets}
        return render(request,'notifications/universe_confirm.html',context=tick_dict)

def ticket_status_today(request):
    #d = datetime.now()
    #print(d)
    #print(d.date())
    today=str(date.today())
    Total_tick = Ticket.objects.values('Ticket_ID').filter(Estimated_Delivery_Date__icontains=today)
    #withsu = Ticket.objects.filter(Ticket_ID__in=Total_tick)
    Confirmed_Tickets = Confirmed_Ticket.objects.values('Ticket_ID').filter(updated_time__icontains=today)
    not_confirmed_ticket = Total_tick.difference(Confirmed_Tickets)
    #Confirmed_Tickets = Confirmed_Ticket.objects.filter(updated_time__icontains=date.today())
    Confirmed_Tickets = Ticket.objects.filter(Ticket_ID__in=Confirmed_Tickets)
    not_confirmed_ticket = Ticket.objects.filter(Ticket_ID__in=not_confirmed_ticket)
    #firmed_Tickets = Ticket.objects.filter(Ticket_ID__in=Confirmed_Tickets)
    #print(firmed_Tickets)
    #joined_queryset=Confirmed_Ticket.objects.raw('SELECT notifications_confirmed_ticket.id,notifications_confirmed_ticket.Ticket_ID,notifications_ticket.Subject,notifications_ticket.Full_name,notifications_ticket.Company_Name,notifications_confirmed_ticket.updated_time FROM notifications_confirmed_ticket LEFT JOIN notifications_ticket ON notifications_confirmed_ticket.Ticket_ID=notifications_ticket.Ticket_ID')
    tick_dict = {'Ticket':Confirmed_Tickets,'Ticketsnot':not_confirmed_ticket}
    return render(request,'notifications/status.html',context=tick_dict)

@login_required(login_url = 'login_user')
def tomorrow_braindesk(request):
    lis=['Braindesk Report Refresh Request','Braindesk Request']
    if request.method == "POST":
        tomorrow=str(date.today()+timedelta(days=1))
        tickets = Ticket.objects.filter(Estimated_Delivery_Date__icontains=tomorrow,Type__in=lis)
        tick_dict = {'Ticket':tickets,'name':"Braindesk Team","url":"tomorrow/braindesk-deliverables","day":"Tomorrow"}
        #send_mail(
        #'You have Deliverable Today !!!',
        #"Good Eve !!!",
        #settings.EMAIL_HOST_USER,
        #['kesavan.ramalingam@draup.com'],
        #fail_silently=False)
        #print("mail sent sucess fully")

notifications/templates/notifications/braindesk_confirm.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <title>Draup-Remainders</title>
    <link rel = "icon" href ="{% static '/images/title-logo.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style media="screen">
      .container {
  padding: 2rem 0rem;
}

h4 {
  margin: 2rem 0rem 1rem;
}

.table-image {
  td, th {
    vertical-align: middle;
  }
}
    </style>
  </head>
  <body>
    <div class="container">
      <p>Hi Braindesk User,</p>
      <p>Please select the check box and click submit to save your response..</p>
      <br>
<form  method="post">
<div class="row">
  <div class="col-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">S.No.</th>
          <th  scope="col">Ticket No.</th>
          <th  scope="col">Subject</th>
          <th  scope="col">Stakeholder</th>
          <th  scope="col">Company</th>
          <th  scope="col">Delivery Date</th>
        </tr>
      </thead>
      {% for entry in Ticket %}
      <tbody>
        <tr>
          <td style="text-align:center"><input type="checkbox"  name="Ticket_ID" value={{entry.Ticket_ID}}>
          <td  style="text-align:center">{{entry.Ticket_ID}}</td>
          <td>{{entry.Subject}}</td>
          <td>{{entry.Full_name}}</td>
          <td>{{entry.Company_Name}}</td>
          <td style="text-align:center">{{entry.Estimated_Delivery_Date}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
  {% csrf_token %}
  <br><input onclick="return confirm('Are you sure do you want to continue ?');" class="btn btn-primary" type="submit" value="Submit">
</form>
</div>
  </body>
</html>

notifications/templates/notifications/landingpage.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Draup-Remainders</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="style.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/landingpage.css' %}">
		<link rel = "icon" href ="{% static '/images/title-logo.ico' %}">
</head>
<body>

	<div class="header">
     <div class="navbar">
         <div class="logo">
             <a href="https://platform.draup.com/"><img src="{% static '/images/draup-logo.png' %}"></a>
         </div>
         <div class="menu">
             <ul>
                 <a href="{%url 'home:todaydeliverables'%}"><li>Sales Remainders</li></a>
                 <li>Talent Remainers</li>
                 <li>Support</li>
             </ul>
         </div>
         <div class="login-btn">Welcome {{user}}</div>
     </div>

     <div class="banner">
         <div class="app-text">
					 	<br>
						<br>
						<br>
             <h1>A Data Product with a Human Touch</h1>
						 <a href="https://platform.draup.com/"><br><div class="platform">Go to Platform</div></a>
						 <div class="app-picture">
             <img src="{% static '/images/10.jpg' %}" width="540" height="390">
						</div>
         </div>
     </div>
    </div>
</body>
</html>

notifications/templates/notifications/today_braindesk_deliverables.html
<title>Draup-Remainders</title>
{% extends 'notifications/base.html' %}

{% block body_block %}
<div class="tab">
  <nav>
     <a href = "{%url 'home:today_braindesk'%}">Braindesk</a> |
     <a href = "{%url 'home:today_universe'%}">Universe</a> |
     <a href = "{%url 'home:today_others'%}">Others</a> |
  </nav>
  <br>
  <h1>Braindesk Deliverables !!</h1>
  <br>
    <table id="customers">
    <tr>
      <th style="text-align:center">S.No.</th>
      <th style="text-align:center">Ticket No.</th>
      <th style="text-align:center">Subject</th>
      <th style="text-align:center">Stakeholder</th>
      <th style="text-align:center">Company</th>
      <th style="text-align:center">Delivery Date</th>
      <th style="text-align:center">Type</th>
    </tr>
    {% for entry in Ticket %}
    <tr>
      <td style="text-align:center">{{forloop.counter}}</td>
      <td  style="text-align:center">{{entry.Ticket_ID}}</td>
      <td>{{entry.Subject}}</td>
      <td>{{entry.Full_name}}</td>
      <td>{{entry.Company_Name}}</td>
      <td style="text-align:center">{{entry.Estimated_Delivery_Date}}</td>
      <td>{{entry.Type}}</td>
    </tr>
    {% endfor %}
  </table>
  <form  method="post">
    {% csrf_token %}
    <br><input onclick="return confirm('Are you sure do you want to continue ?');" class="btn btn-primary" type="submit" value="Send Notification">
  </form>
</div>
{% endblock %}

notifications/templates/notifications/today_deliverables.html
<title>Draup-Remainders</title>
{% extends 'notifications/base.html' %}

{% block body_block %}

<div class="tab">
  <nav>
     <a href = "{%url 'home:today_braindesk'%}">Braindesk</a> |
     <a href = "{%url 'home:today_universe'%}">Universe</a> |
     <a href = "{%url 'home:today_others'%}">Others</a> |
  </nav>
  <br>
  <h1>Today Deliverables !!</h1>
  <br>
    <table id="customers">
    <tr>
      <th style="text-align:center">S.No.</th>
      <th style="text-align:center">Ticket No.</th>
      <th style="text-align:center">Subject</th>
      <th style="text-align:center">Stakeholder</th>
      <th style="text-align:center">Company</th>
      <th style="text-align:center">Delivery Date</th>
      <th style="text-align:center">Type</th>
    </tr>
    {% for entry in Ticket %}
    <tr>
      <td style="text-align:center">{{forloop.counter}}</td>
      <td  style="text-align:center">{{entry.Ticket_ID}}</td>
      <td>{{entry.Subject}}</td>
      <td>{{entry.Full_name}}</td>
      <td>{{entry.Company_Name}}</td>
      <td style="text-align:center">{{entry.Estimated_Delivery_Date}}</td>
      <td>{{entry.Type}}</td>
    </tr>
    {% endfor %}
  </table>
  <br><a class="btn btn-primary" href="{%url 'home:upload'%}">Refresh this Table</a>
  <br>
  <br>
</div>
{% endblock %}

notifications/templates/notifications/today_others_deliverables.html
<title>Draup-Remainders</title>
{% extends 'notifications/base.html' %}

{% block body_block %}
<div class="tab">
  <nav>
     <a href = "{%url 'home:today_braindesk'%}">Braindesk</a> |
     <a href = "{%url 'home:today_universe'%}">Universe</a> |
     <a href = "{%url 'home:today_others'%}">Others</a> |
  </nav>
  <br>
  <h1> Deliverables !!</h1>
  <br>
    <table id="customers">
    <tr>
      <th style="text-align:center">S.No.</th>
      <th style="text-align:center">Ticket No.</th>
      <th style="text-align:center">Subject</th>
      <th style="text-align:center">Stakeholder</th>
      <th style="text-align:center">Company</th>
      <th style="text-align:center">Delivery Date</th>
      <th style="text-align:center">Type</th>
    </tr>
    {% for entry in Ticket %}
    <tr>
      <td style="text-align:center">{{forloop.counter}}</td>
      <td  style="text-align:center">{{entry.Ticket_ID}}</td>
      <td>{{entry.Subject}}</td>
      <td>{{entry.Full_name}}</td>
      <td>{{entry.Company_Name}}</td>
      <td style="text-align:center">{{entry.Estimated_Delivery_Date}}</td>
      <td>{{entry.Type}}</td>
    </tr>
    {% endfor %}
  </table>
  <form  method="post">
    {% csrf_token %}
    <br><input onclick="return confirm('Are you sure do you want to continue ?');" class="btn btn-primary" type="submit" value="Send Notification">
  </form>
</div>
{% endblock %}

notifications/templates/notifications/today_universe_deliverables.html
<title>Draup-Remainders</title>
{% extends 'notifications/base.html' %}

{% block body_block %}

<div class="tab">
  <nav>
     <a href = "{%url 'home:today_braindesk'%}">Braindesk</a> |
     <a href = "{%url 'home:today_universe'%}">Universe</a> |
     <a href = "{%url 'home:today_others'%}">Others</a> |
  </nav>
  <br>
  <h1>Universe Deliverables !!</h1>
  <br>
    <table id="customers">
    <tr>
      <th style="text-align:center">S.No.</th>
      <th style="text-align:center">Ticket No.</th>
      <th style="text-align:center">Subject</th>
      <th style="text-align:center">Stakeholder</th>
      <th style="text-align:center">Company</th>
      <th style="text-align:center">Delivery Date</th>
      <th style="text-align:center">Type</th>
    </tr>
    {% for entry in Ticket %}
    <tr>
      <td style="text-align:center">{{forloop.counter}}</td>
      <td  style="text-align:center">{{entry.Ticket_ID}}</td>
      <td>{{entry.Subject}}</td>
      <td>{{entry.Full_name}}</td>
      <td>{{entry.Company_Name}}</td>
      <td style="text-align:center">{{entry.Estimated_Delivery_Date}}</td>
      <td>{{entry.Type}}</td>
    </tr>
    {% endfor %}
  </table>
  <form  method="post">
    {% csrf_token %}
    <br><input onclick="return confirm('Are you sure do you want to continue ?');" class="btn btn-primary" type="submit" value="Send Notification">
  </form>
</div>
{% endblock %}

notifications/templates/notifications/tomorrow_braindesk_deliverables.html
<title>Draup-Remainders</title>
{% extends 'notifications/base.html' %}

{% block body_block %}

<div class="tab">
  <nav>
     <a href = "{%url 'home:tomorrow_braindesk'%}">Braindesk</a> |
     <a href = "{%url 'home:tomorrow_universe'%}">Universe</a> |
     <a href = "{%url 'home:tomorrow_others'%}">Others</a> |
  </nav>
  <br>
  <h1>Braindesk Deliverables !!</h1>
  <br>
    <table id="customers">
    <tr>
      <th style="text-align:center">S.No.</th>
      <th style="text-align:center">Ticket No.</th>
      <th style="text-align:center">Subject</th>
      <th style="text-align:center">Stakeholder</th>
      <th style="text-align:center">Company</th>
      <th style="text-align:center">Delivery Date</th>
      <th style="text-align:center">Type</th>
    </tr>
    {% for entry in Ticket %}
    <tr>
      <td style="text-align:center">{{forloop.counter}}</td>
      <td  style="text-align:center">{{entry.Ticket_ID}}</td>
      <td>{{entry.Subject}}</td>
      <td>{{entry.Full_name}}</td>
      <td>{{entry.Company_Name}}</td>
      <td style="text-align:center">{{entry.Estimated_Delivery_Date}}<
      <td>{{entry.Type}}</td>
    </tr>
    {% endfor %}
  </table>

  <form  method="post">
    {% csrf_token %}
    <br><input onclick="return confirm('Are you sure do you want to continue ?');" class="btn btn-primary" type="submit" value="Send Notification">
  </form>
  
</div>
{% endblock %}

notifications/templates/notifications/tomorrow_others_deliverables.html
<title>Draup-Remainders</title>
{% extends 'notifications/base.html' %}

{% block body_block %}
<div class="tab">
  <nav>
     <a href = "{%url 'home:tomorrow_braindesk'%}">Braindesk</a> |
     <a href = "{%url 'home:tomorrow_universe'%}">Universe</a> |
     <a href = "{%url 'home:tomorrow_others'%}">Others</a> |
  </nav>
  <br>
  <h1> Deliverables !!</h1>
  <br>
    <table id="customers">
    <tr>
      <th style="text-align:center">S.No.</th>
      <th style="text-align:center">Ticket No.</th>
      <th style="text-align:center">Subject</th>
      <th style="text-align:center">Stakeholder</th>
      <th style="text-align:center">Company</th>
      <th style="text-align:center">Delivery Date</th>
      <th style="text-align:center">Type</th>
    </tr>
    {% for entry in Ticket %}
    <tr>
      <td style="text-align:center">{{forloop.counter}}</td>
      <td  style="text-align:center">{{entry.Ticket_ID}}</td>
      <td>{{entry.Subject}}</td>
      <td>{{entry.Full_name}}</td>
      <td>{{entry.Company_Name}}</td>
      <td style="text-align:center">{{entry.Estimated_Delivery_Date}}</td>
      <td>{{entry.Type}}</td>
    </tr>
    {% endfor %}
  </table>

  <form  method="post">
    {% csrf_token %}
    <br><input onclick="return confirm('Are you sure do you want to continue ?');" class="btn btn-primary" type="submit" value="Send Notification">
  </form>

</div>
{% endblock %}

notifications/templates/notifications/tomorrow_universe_deliverables.html
<title>Draup-Remainders</title>
{% extends 'notifications/base.html' %}

{% block body_block %}
<div class="tab">
  <nav>
     <a href = "{%url 'home:tomorrow_braindesk'%}">Braindesk</a> |
     <a href = "{%url 'home:tomorrow_universe'%}">Universe</a> |
     <a href = "{%url 'home:tomorrow_others'%}">Others</a> |
  </nav>
  <br>
  <h1>Universe Deliverables !!</h1>
  <br>
    <table id="customers">
    <tr>
      <th style="text-align:center">S.No.</th>
      <th style="text-align:center">Ticket No.</th>
      <th style="text-align:center">Subject</th>
      <th style="text-align:center">Stakeholder</th>
      <th style="text-align:center">Company</th>
      <th style="text-align:center">Delivery Date</th>
      <th style="text-align:center">Type</th>
    </tr>
    {% for entry in Ticket %}
    <tr>
      <td style="text-align:center">{{forloop.counter}}</td>
      <td  style="text-align:center">{{entry.Ticket_ID}}</td>
      <td>{{entry.Subject}}</td>
      <td>{{entry.Full_name}}</td>
      <td>{{entry.Company_Name}}</td>
      <td style="text-align:center">{{entry.Estimated_Delivery_Date}}</td>
      <td>{{entry.Type}}</td>
    </tr>
    {% endfor %}
  </table>

  <form  method="post">
    {% csrf_token %}
    <br><input onclick="return confirm('Are you sure do you want to continue ?');" class="btn btn-primary" type="submit" value="Send Notification">
  </form>

</div>
{% endblock %}